import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import Header from "components/Header";
import Footer from "components/Footer";
import ProductFilterProvider from "context/ProductFilterContext";
import CartStateProvider from "context/CartStateContext";
import AuthContextProvider from "context/AuthContext";
import ChatBox from "components/ChatBox";
import AuthProvider from "context/AuthProvider";
import FetchContextProvider from "context/FetchContext";

export const metadata: Metadata = {
  title: "IN.EX SHOP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/in.ex-shop.png" type="image/<generated></generated>" sizes="<generated>" />
      </head>
      <AuthProvider>
        <AuthContextProvider>
          <FetchContextProvider>
            <CartStateProvider>
              <ProductFilterProvider>
                <body>
                  <Header />
                  {children}
                  <ChatBox />
                  <Footer />
                  <ToastContainer />
                </body>
              </ProductFilterProvider>
            </CartStateProvider>
          </FetchContextProvider>
        </AuthContextProvider>
      </AuthProvider>
    </html>
  );
}
