services:
  index-shop:
    image: nghiakydiem/inex-shop:1.4
    ports:
      - "8080:5000"
    environment:
      PORT: 5000
      BASE_URL: ${BASE_URL:-http://localhost:5000}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
      MONGO_DATABASE_URL: ${MONGO_DATABASE_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET_KEY: ${GOOGLE_SECRET_KEY}